baseURL = "https://rfcswelove.com/"
languageCode = "en-us"
title = "RFCs We Love"

paginate = 5
Copyright = "All rights reserved - 2019"
canonifyurls = false

[params]
  description = "RFCs We Love"
  author = "Michael Kehoe"
  authorlocation = "San Francisco, CA"
  authorwebsite = "https://rfcswelove.com/"
  hideHUGOSupport = true
