baseURL = "https://rfcswelove.com/"
languageCode = "en-us"
title = "RFCs We Love"

paginate = 5
Copyright = "All rights reserved - 2019"
canonifyurls = false

[params]
  description = "RFCs We Love"
  author = "Michael Kehoe"
  authorlocation = "San Francisco, CA"
  authorwebsite = "https://rfcswelove.com/"
  hideHUGOSupport = true

[[menu.main]]
  name = "Home"
  url  = "/"
  weight = 0

[[menu.main]]
  name = "About"
  url  = "about"
  weight = 5

[[menu.main]]
  name = "Blog"
  url  = "post/"
  weight = 10
